"""Tests for the two POSIX parent-death gaps in `run_worker_loop`.

Both end the same way -- a worker orphaned forever holding an exclusive
Kuzu/LanceDB lock -- but they are distinct bugs with distinct fixes:

* the ARM-WINDOW race (`TestArmWindowRace`), where the parent dies before the
  child can arm anything at all; and
* the FORKSERVER ANCHOR gap (`TestForkserverAnchorGap`, added 2026-07-29),
  where everything arms successfully and still points at the wrong process.

Root cause of the first: `set_pdeathsig()` arms `prctl(PR_SET_PDEATHSIG,
SIGTERM)` from INSIDE the child, at the top of `run_worker_loop`.
`PR_SET_PDEATHSIG` is not retroactive -- it only fires for a parent death that
happens AFTER the prctl call. Workers here are `spawn`-started, so there is a
real window (re-exec python, import chain, unpickle) between `Process.start()`
in the parent and the arm in the child. A parent that dies in that window (an
OOM kill being the realistic trigger) delivers no signal, ever. Worse,
`set_pdeathsig()` returns True regardless -- the syscall itself succeeded --
which SUPPRESSES the `start_parent_liveness_watchdog()` fallback at the call
site. Net result: an orphaned worker holding an exclusive Kuzu/LanceDB lock
forever. This is the POSIX twin of the Windows orphan incident that
`test_windows_parent_death_watchdog.py` covers.

Root cause of the second: `prctl(PR_SET_PDEATHSIG)` anchors to the caller's
**OS** parent. Under `forkserver` that is the FORK SERVER, not the launching
process, and the fork server outlives a launching process that dies -- it is
merely reparented -- so the signal never arrives even though prctl armed
successfully and reported success. The pre-existing portable fallback cannot
cover for it either: `start_parent_liveness_watchdog` polls `os.getppid()`,
which resolves to that same still-alive fork server. Fixed by
`start_parent_sentinel_watchdog`, which polls the multiprocessing parent
sentinel -- the signal that reads the REAL parent's death correctly, and the one
`parent_already_exited` already trusts at startup.

Why these tests are structured the way they are:

* Real `spawn`/`forkserver` subprocesses running the REAL `run_worker_loop`,
  and a real `SIGKILL` of a real parent. The bug is entirely about kernel
  process lifecycle; a mock of `prctl` or of `parent_process()` would test the
  mock, not the guarantee.
* The parent kills ITSELF with `SIGKILL` rather than being killed from the
  test process, so the death is indistinguishable from an OOM kill (no
  handlers, no atexit, no chance to clean up its children).
* The worker deliberately stalls before entering `run_worker_loop`, which
  widens the naturally microsecond-wide arm window into a deterministic one.
  Without the stall this race reproduces only by luck.
* Liveness is pinned to ONE process via `/proc/<pid>/stat` field 22
  (`starttime`), never by PID number alone -- otherwise PID reuse could make a
  dead worker look alive (false failure) or, in the survival test, make a
  reused PID look like a surviving worker (false PASS, the dangerous
  direction).

`TestNoFalsePositive` is the load-bearing regression guard for the OTHER
failure mode: the naive version of this fix ("compare `os.getppid()` to the
launch-time parent pid") reports "parent dead" for a perfectly healthy parent
under the `forkserver` start method, where the two differ BY DESIGN because
the child's OS parent is the fork server, not the launching process. CPython
3.14 makes `forkserver` the default on Linux, so that naive fix would
`os._exit(0)` every worker at startup. Those tests must keep passing under
`forkserver` specifically.
"""

from __future__ import annotations

import os
import queue as _queue
import signal
import subprocess
import sys
import threading
import time
from pathlib import Path

import pytest

pytestmark = pytest.mark.skipif(
    sys.platform != "linux", reason="POSIX parent-death race; /proc and prctl are Linux-only"
)

# Derived from the module under test rather than hard-coded, so the suite also
# runs from a copied tree (e.g. a WSL native-filesystem scratch copy).
_REPO_ROOT = str(Path(__file__).resolve().parents[2])

# Long enough that the parent is reliably dead before the worker reaches
# ``run_worker_loop``; short enough to keep the suite quick.
_STALL_SECONDS = 5.0
_KILL_AFTER_SECONDS = 1.5

_PARENT_SCRIPT = '''\
"""Generated by test_linux_parent_death_race.py. Stands in for the real
main process that owns a cognee_db_workers subprocess session."""
import multiprocessing as mp
import os
import signal
import sys
import time

sys.path.insert(0, {repo_root!r})

from cognee_db_workers.harness import run_worker_loop

STALL = {stall!r}
METHOD = {method!r}
KILL_MODE = {kill_mode!r}
KILL_AFTER = {kill_after!r}
MARKER_PATH = {marker_path!r}


def _worker(req_q, resp_q):
    # The deliberate stall. In production this window is filled by spawn's own
    # re-exec + import + unpickle work; here it is explicit so the race is
    # deterministic rather than a microsecond-wide coin flip.
    time.sleep(STALL)
    # The REAL loop -- not a stand-in. Empty dispatch + no init is enough: the
    # arming block under test runs before either is touched.
    # MARKER: proves the child actually REACHED the guard.
    # Without this the only assertion is "the process is gone", which is also
    # true when the child dies during the spawn bootstrap (unpickling, imports)
    # because the SIGKILL landed inside it -- so the test would PASS with the
    # fix deleted. "The process is gone" is not "the guard fired".
    open(MARKER_PATH, "w").close()
    run_worker_loop({{}}, req_q, resp_q)


if __name__ == "__main__":
    ctx = mp.get_context(METHOD)
    req_q = ctx.Queue()
    resp_q = ctx.Queue()
    # daemon=True mirrors the real KuzuSubprocessSession/LanceDB spawn. It is
    # NOT a safety net here: daemon children are reaped by the parent's atexit
    # handler, which a SIGKILLed parent never runs.
    proc = ctx.Process(target=_worker, args=(req_q, resp_q), daemon=True)
    proc.start()
    print("PID %d" % proc.pid, flush=True)

    if KILL_MODE == "during_arm_window":
        # Die while the worker is still stalling, i.e. BEFORE it can arm
        # pdeathsig. SIGKILL to self == OOM-killer semantics.
        time.sleep(KILL_AFTER)
        print("KILLING_SELF", flush=True)
        os.kill(os.getpid(), signal.SIGKILL)

    # Every other mode needs the worker fully up first.
    try:
        resp_q.get(timeout=30)
        print("READY", flush=True)
    except Exception as exc:
        print("NO_READY %s" % type(exc).__name__, flush=True)

    if KILL_MODE == "after_arm":
        time.sleep(KILL_AFTER)
        print("KILLING_SELF", flush=True)
        os.kill(os.getpid(), signal.SIGKILL)

    # KILL_MODE == "never": stay alive so the worker's survival can be
    # observed against a genuinely healthy parent.
    time.sleep(120)
'''


def _proc_identity(pid: int):
    """``(state, starttime)`` from ``/proc/<pid>/stat``, or ``None`` if gone.

    ``starttime`` (field 22, clock ticks since boot) is what makes this
    PID-reuse-proof: it is fixed for the life of one process, so a PID that has
    been recycled by an unrelated process reports a different value and is
    correctly treated as "the process we were watching is gone".

    Field 2 (``comm``) is an arbitrary string wrapped in parentheses and may
    itself contain spaces and parentheses, so parsing starts after the LAST
    ``)``. The remaining whitespace-separated tokens begin at field 3, hence
    field N is at index ``N - 3``: state -> 0, starttime -> 19.
    """
    try:
        with open("/proc/%d/stat" % pid, "rb") as fh:
            raw = fh.read()
    except (FileNotFoundError, ProcessLookupError, PermissionError):
        return None
    try:
        fields = raw[raw.rindex(b")") + 1 :].split()
        return fields[0].decode(), fields[19].decode()
    except (ValueError, IndexError):
        return None


def _os_parent_pid(pid: int):
    """Field 4 (``ppid``) of ``/proc/<pid>/stat`` — the process prctl anchors to.

    Same parsing rules as ``_proc_identity``: tokens start at field 3, so field
    N sits at index ``N - 3`` and ppid is index 1. Used to ASSERT the forkserver
    anchoring divergence was actually present in a given run rather than
    assuming the start method behaved as expected — the test for a bug caused by
    a wrong anchor must not itself take the anchor on faith.
    """
    try:
        with open("/proc/%d/stat" % pid, "rb") as fh:
            raw = fh.read()
    except (FileNotFoundError, ProcessLookupError, PermissionError):
        return None
    try:
        return int(raw[raw.rindex(b")") + 1 :].split()[1])
    except (ValueError, IndexError):
        return None


def _watchdog_thread_count() -> int:
    """How many sentinel-watchdog threads are live in THIS process right now.

    Tests assert on the DELTA across a test, never on an absolute zero: a
    mutant that wrongly starts a watcher leaks a daemon thread that outlives
    the test which started it, and an absolute assertion would then fail every
    later test too, destroying the attribution a mutation run depends on.
    """
    return sum(1 for t in threading.enumerate() if t.name == "parent-sentinel-watchdog")


def _require_identity(pid: int) -> str:
    ident = _proc_identity(pid)
    assert ident is not None, f"worker pid {pid} was already gone when the test tried to pin it"
    return ident[1]


def _is_gone(pid: int, starttime: str) -> bool:
    """True once THAT specific process is no longer running.

    Zombies count as gone: the worker has exited: it is merely un-reaped
    because its parent is dead. A different ``starttime`` means the PID was
    recycled, which also means the original is gone.
    """
    ident = _proc_identity(pid)
    if ident is None:
        return True
    state, current_starttime = ident
    if current_starttime != starttime:
        return True
    return state == "Z"


class _LineReader:
    """Non-blocking line access to a child's stdout.

    ``readline()`` on a pipe blocks forever if the writer dies without writing,
    which would hang the whole suite instead of failing it. A reader thread
    plus a queue turns that into a bounded, reportable timeout.
    """

    def __init__(self, proc: subprocess.Popen):
        self._q: "_queue.Queue[str]" = _queue.Queue()
        self._proc = proc
        self._t = threading.Thread(target=self._pump, daemon=True)
        self._t.start()

    def _pump(self) -> None:
        try:
            for line in self._proc.stdout:
                self._q.put(line.strip())
        except Exception:
            pass

    def next_line(self, timeout: float = 30.0) -> str:
        try:
            return self._q.get(timeout=timeout)
        except _queue.Empty:
            raise AssertionError(
                f"parent process printed no further output within {timeout}s "
                f"(exit code so far: {self._proc.poll()})"
            )


def _write_parent_script(tmp_path, *, method: str, kill_mode: str, stall: float) -> str:
    path = tmp_path / f"parent_{method}_{kill_mode}.py"
    path.write_text(
        _PARENT_SCRIPT.format(
            repo_root=_REPO_ROOT,
            stall=stall,
            method=method,
            kill_mode=kill_mode,
            kill_after=_KILL_AFTER_SECONDS,
            marker_path=str(path) + '.reached',
        )
    )
    return str(path)


def _launch_parent(script: str) -> subprocess.Popen:
    return subprocess.Popen(
        [sys.executable, script],
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
    )


def _reap(pid: int, starttime: str | None = None) -> None:
    """Kill a test-spawned process, verifying identity first.

    CORRECTED 2026-07-28: this previously did a bare ``os.kill(pid, SIGKILL)``
    with no starttime check -- violating the discipline THIS FILE states at the
    top ("never by PID number alone"). By the time cleanup runs the pid has very
    likely already exited, and Linux recycles pids, so a bare kill can SIGKILL an
    unrelated process on the test host. Same class as the machine-wide PID-reuse
    rule that the descendant-walk reaper had to be fixed for.

    ``starttime`` is optional only so older call sites keep working; pass it.
    """
    if starttime is not None:
        ident = _proc_identity(pid)
        if ident is None:
            return  # already gone -- nothing to kill
        if ident[1] != starttime:
            return  # PID RECYCLED: this is a different process. Do not kill it.
    try:
        os.kill(pid, signal.SIGKILL)
    except (ProcessLookupError, PermissionError, OSError):
        pass


class TestArmWindowRace:
    """The reported bug: parent dies BEFORE the worker can arm pdeathsig."""

    @pytest.mark.parametrize("method", ["spawn", "forkserver"])
    def test_worker_exits_when_parent_dies_before_pdeathsig_is_armed(self, tmp_path, method):
        script = _write_parent_script(
            tmp_path, method=method, kill_mode="during_arm_window", stall=_STALL_SECONDS
        )
        parent = _launch_parent(script)
        worker_pid = None
        try:
            reader = _LineReader(parent)
            line = reader.next_line()
            assert line.startswith("PID "), f"unexpected first line from parent: {line!r}"
            worker_pid = int(line.split()[1])
            starttime = _require_identity(worker_pid)

            assert reader.next_line() == "KILLING_SELF"
            parent.wait(timeout=15)
            assert parent.returncode == -signal.SIGKILL, (
                f"parent did not die by SIGKILL (returncode={parent.returncode}); "
                "the race was never actually set up"
            )

            # Budget: the remaining stall, plus generous slack for a loaded box.
            deadline = time.monotonic() + _STALL_SECONDS + 25.0
            while time.monotonic() < deadline:
                if _is_gone(worker_pid, starttime):
                    # The worker is gone -- but WHY? "gone" is also true if the SIGKILL
                    # landed inside the spawn bootstrap (unpickle/imports), which would
                    # make this test PASS with the fix deleted. The marker is written
                    # immediately before run_worker_loop, so its presence proves the
                    # child actually REACHED the guard and then exited, rather than
                    # dying on the way there. "The process is gone" is not "the guard
                    # fired" -- the same "a substring is not the property" trap.
                    assert os.path.exists(script + ".reached"), (
                        "worker died WITHOUT reaching run_worker_loop -- the SIGKILL "
                        "landed during bootstrap, so this run proves nothing about the "
                        "guard. Raise the stall or _KILL_AFTER_SECONDS."
                    )
                    return
                time.sleep(0.1)
            pytest.fail(
                f"[{method}] worker pid {worker_pid} was STILL RUNNING "
                f"{_STALL_SECONDS + 25.0:.0f}s after its parent was SIGKILLed during the "
                "pdeathsig arm window. This is the orphaned-worker-holding-a-DB-lock bug: "
                "prctl(PR_SET_PDEATHSIG) is not retroactive, and set_pdeathsig() returning "
                "True suppresses the polling-watchdog fallback."
            )
        finally:
            if worker_pid is not None:
                _reap(worker_pid)
            if parent.poll() is None:
                parent.kill()


class TestNoFalsePositive:
    """The forkserver regression guard.

    A healthy parent must never cause a worker to exit. This is exactly what
    the naive `os.getppid() != launch_ppid` fix breaks: under `forkserver` the
    worker's OS parent is the fork server, so `getppid()` differs from the
    launching process's pid permanently, with the parent in perfect health --
    measured on this target (WSL Ubuntu / CPython 3.14.4), parent alive
    throughout::

        spawn        parent_process().pid=199682  getppid()=199682
        fork         parent_process().pid=199682  getppid()=199682
        forkserver   parent_process().pid=199682  getppid()=199706   <-- differ

    If someone re-introduces that comparison as the PRIMARY signal, the
    forkserver parametrisation below fails: every worker exits at startup.
    """

    @pytest.mark.parametrize("method", ["spawn", "fork", "forkserver"])
    def test_worker_survives_while_parent_is_alive(self, tmp_path, method):
        script = _write_parent_script(tmp_path, method=method, kill_mode="never", stall=0.0)
        parent = _launch_parent(script)
        worker_pid = None
        try:
            reader = _LineReader(parent)
            line = reader.next_line()
            assert line.startswith("PID "), f"unexpected first line from parent: {line!r}"
            worker_pid = int(line.split()[1])
            starttime = _require_identity(worker_pid)

            status = reader.next_line()
            assert status == "READY", (
                f"[{method}] worker never reported READY ({status!r}) -- it exited or hung "
                "during startup even though its parent is alive. Under forkserver this is "
                "the signature of a getppid()-based parent-death check firing on a healthy "
                "parent."
            )

            # Watch for a while: a false positive kills the worker essentially
            # immediately, so a steady 6s is a decisive observation.
            deadline = time.monotonic() + 6.0
            while time.monotonic() < deadline:
                assert not _is_gone(worker_pid, starttime), (
                    f"[{method}] worker pid {worker_pid} exited while its parent was still "
                    "alive -- parent_already_exited() produced a FALSE POSITIVE. This is the "
                    "outage-shaped failure mode: every worker dies at startup."
                )
                time.sleep(0.25)
            assert parent.poll() is None, "the parent died on its own; test setup is invalid"
        finally:
            if worker_pid is not None:
                _reap(worker_pid)
            if parent.poll() is None:
                parent.kill()


class TestNormalPathNotRegressed:
    """pdeathsig must still do its job when the parent dies AFTER arming.

    `spawn` only, deliberately, and NOT because forkserver is untested here --
    `TestArmWindowRace` covers forkserver and passes. It is because under
    `forkserver` this assertion is simply not true of the code, and measuring
    it is how that was established. `prctl(PR_SET_PDEATHSIG)` anchors to the
    caller's OS parent, and under `forkserver` the worker's OS parent is the
    FORK SERVER, not the launching process. Measured on WSL Ubuntu / CPython
    3.14.4, launching process SIGKILLed at t=3s::

        forkserver  worker=200042  os_parent(getppid)=200041 (fork server)
                                   mp_parent_process_pid=200039 (real parent)
        t= 2.00  os_parent(200041)=alive  real_parent(200039)=alive  sentinel=True
        t= 4.00  os_parent(200041)=alive  real_parent(200039)=GONE   sentinel=False
        t=18.00  os_parent(200041)=alive  real_parent(200039)=GONE   sentinel=False
        SURVIVED_FULL_20s

    The fork server outlived the launching process (it was merely reparented,
    200039 -> 200008), so the worker's pdeathsig never fired and the worker
    orphaned. That is a SECOND, pre-existing gap, distinct from the arm-window
    race this change fixes, and it is out of scope here: cognee's real workers
    pin `mp.get_context("spawn")` explicitly (kuzu and lancedb
    `subprocess/proxy.py`), so the forkserver anchoring gap is latent, not
    live. Note the sentinel column above -- it read the real parent's death
    correctly at t=4 in exactly the case prctl could not, which is why
    `parent_already_exited` is built on the sentinel and not on prctl or
    getppid.

    No characterization test asserts the survival above: doing so would lock
    the bug in and go red the day someone fixes it properly.

    SUPERSEDED 2026-07-29 -- state as of `0ccdc608e`. Everything above is still
    an accurate account of the MEASUREMENT, and the "out of scope here" /
    "latent, not live" framing was true when written. It is no longer the state
    of the code: that day arrived. `start_parent_sentinel_watchdog` closes the
    anchoring gap, and `TestForkserverAnchorGap` below is the test the last
    paragraph declined to write -- it asserts the OPPOSITE of the trace above,
    which is exactly why writing it then would have locked the bug in. The
    survival trace is retained deliberately: it is the control measurement that
    makes the inverted assertion meaningful, and re-measuring it is how the fix
    was verified rather than assumed.

    This class keeps its `spawn`-only parametrisation. The mechanism it guards
    is prctl itself, which under forkserver is genuinely not what does the work
    -- adding forkserver here would silently retarget the test at the sentinel
    watchdog while its name still claimed to cover the kernel signal path.
    """

    @pytest.mark.parametrize("method", ["spawn"])
    def test_pdeathsig_kills_worker_when_parent_dies_after_arming(self, tmp_path, method):
        script = _write_parent_script(tmp_path, method=method, kill_mode="after_arm", stall=0.0)
        parent = _launch_parent(script)
        worker_pid = None
        try:
            reader = _LineReader(parent)
            line = reader.next_line()
            assert line.startswith("PID "), f"unexpected first line from parent: {line!r}"
            worker_pid = int(line.split()[1])
            starttime = _require_identity(worker_pid)

            # READY proves the worker got past the arming block, so the death
            # below lands strictly AFTER prctl armed -- the normal path.
            assert reader.next_line() == "READY"
            assert reader.next_line() == "KILLING_SELF"
            parent.wait(timeout=15)
            assert parent.returncode == -signal.SIGKILL

            deadline = time.monotonic() + 20.0
            while time.monotonic() < deadline:
                if _is_gone(worker_pid, starttime):
                    return
                time.sleep(0.1)
            pytest.fail(
                f"[{method}] worker pid {worker_pid} survived its parent's SIGKILL even though "
                "pdeathsig was armed before the parent died -- the kernel parent-death signal "
                "path has regressed."
            )
        finally:
            if worker_pid is not None:
                _reap(worker_pid)
            if parent.poll() is None:
                parent.kill()


class TestForkserverAnchorGap:
    """The SECOND bug: everything arms, and still points at the wrong process.

    This is `TestNormalPathNotRegressed`'s recorded survival trace, inverted.
    Same scenario in every respect -- worker fully up, READY observed, so prctl
    armed successfully and returned True -- differing only in the start method.
    Under `spawn` the worker dies in ~0.1s; under `forkserver` it used to
    survive indefinitely, because `prctl(PR_SET_PDEATHSIG)` anchors to the OS
    parent and under forkserver that is the fork server, which is merely
    reparented when the launching process dies. Measured on WSL Ubuntu / CPython
    3.14.4 against the code as of `0ccdc608e`, launching process SIGKILLing
    itself 3s after READY::

        method=spawn       worker=6401  anchor=6399 == launching process
                           RESULT: worker DIED 0.00s after the parent's SIGKILL
        method=fork        worker=6406  anchor=6405 == launching process
                           RESULT: worker DIED 0.10s after the parent's SIGKILL
        method=forkserver  worker=6413  anchor=6412 != launching process 6410
                           t= 0.0 .. 18.0  worker=alive  anchor_alive=True
                           RESULT: SURVIVED the full 20s  <-- ORPHANED WORKER

    Note what makes this gap worse than it looks: the portable fallback is not
    a fallback here. `start_parent_liveness_watchdog` polls `os.getppid()` --
    the fork server -- so it reports "parent fine" for precisely this death.
    Before `start_parent_sentinel_watchdog` there was no second line of defence
    at all.

    LATENT, NOT LIVE, at the time of writing, and the test exists anyway: both
    production spawn sites pin `mp.get_context("spawn")` unconditionally
    (kuzu and lancedb `subprocess/proxy.py`). That is a thin guarantee -- one
    new `Process(...)` with no explicit context under Python 3.14 on Linux, where
    `forkserver` is the DEFAULT, makes it live. This test is what stops that
    one-line change from silently reintroducing an orphaned-lock outage.
    """

    @pytest.mark.parametrize("method", ["forkserver"])
    def test_worker_exits_when_parent_dies_and_pdeathsig_anchors_elsewhere(
        self, tmp_path, method
    ):
        script = _write_parent_script(tmp_path, method=method, kill_mode="after_arm", stall=0.0)
        parent = _launch_parent(script)
        worker_pid = None
        starttime = None
        try:
            reader = _LineReader(parent)
            line = reader.next_line()
            assert line.startswith("PID "), f"unexpected first line from parent: {line!r}"
            worker_pid = int(line.split()[1])
            starttime = _require_identity(worker_pid)

            # SETUP ASSERTION, not a behavioural one. The bug under test is
            # "prctl anchors to the wrong process", so the run is only
            # meaningful if the anchor really was wrong in THIS run. Asserting
            # it rather than trusting the start method also means that if a
            # future CPython makes forkserver children direct children of the
            # launching process, this fails loudly as an invalid setup instead
            # of passing vacuously via the spawn code path.
            anchor = _os_parent_pid(worker_pid)
            assert anchor is not None, "worker vanished before its anchor could be read"
            assert anchor != parent.pid, (
                f"[{method}] worker's OS parent is {anchor}, which IS the launching process "
                f"{parent.pid} -- the forkserver anchoring divergence this test targets did "
                "not occur, so a pass here would prove nothing about the sentinel watchdog."
            )

            # READY proves the worker is fully up and past the arming block, so
            # pdeathsig armed and returned True before the parent died. This is
            # NOT the arm-window race.
            assert reader.next_line() == "READY"
            assert reader.next_line() == "KILLING_SELF"
            parent.wait(timeout=15)
            assert parent.returncode == -signal.SIGKILL, (
                f"parent did not die by SIGKILL (returncode={parent.returncode}); "
                "the scenario was never actually set up"
            )

            # The control measurement above ran for 20s and saw no death, so a
            # 25s budget is decisive rather than merely generous.
            deadline = time.monotonic() + 25.0
            while time.monotonic() < deadline:
                if _is_gone(worker_pid, starttime):
                    return
                time.sleep(0.1)
            pytest.fail(
                f"[{method}] worker pid {worker_pid} SURVIVED 25s after its parent was "
                "SIGKILLed, with pdeathsig armed the whole time. prctl anchored to the fork "
                f"server ({anchor}), which outlives the launching process, and "
                "start_parent_liveness_watchdog polls that same pid so it cannot notice "
                "either. This is the orphaned-worker-holding-a-DB-lock bug via the anchoring "
                "door: start_parent_sentinel_watchdog is what is supposed to catch it."
            )
        finally:
            if worker_pid is not None:
                _reap(worker_pid, starttime)
            if parent.poll() is None:
                parent.kill()


class TestParentAlreadyExitedUnitSemantics:
    """Fail-safe contract of the helpers, without spawning anything."""

    def test_returns_false_without_a_baseline(self):
        from cognee_db_workers import harness

        # Not a multiprocessing child at all: no sentinel, no baseline pid.
        # Must NOT claim the parent is dead.
        assert harness.get_original_parent_pid() is None
        assert harness.parent_already_exited(None) is False

    def test_returns_false_on_win32_regardless_of_baseline(self, monkeypatch):
        from cognee_db_workers import harness

        monkeypatch.setattr(harness.sys, "platform", "win32")
        assert harness.parent_already_exited(999999) is False
        assert harness.parent_already_exited(None) is False

    def test_sentinel_absent_reports_unknown_not_dead(self):
        from cognee_db_workers import harness

        # In the main process there is no parent sentinel; the tri-state must
        # be None ("cannot tell"), never False ("dead").
        assert harness._parent_sentinel_alive() is None

    def test_there_is_no_getppid_fallback_at_all(self, monkeypatch):
        """No usable sentinel must mean "unknown", never "dead".

        REPLACES test_getppid_fallback_is_not_used_under_forkserver, which
        asserted the fallback was *gated* correctly. The fallback has since been
        REMOVED outright: its gate read `get_start_method()`, i.e. the
        process-wide DEFAULT context rather than the context that created this
        child, so a process defaulting to spawn while launching via forkserver
        would pass the gate and then evaluate a comparison that differs BY
        DESIGN -- killing every healthy worker at startup.

        A gate on the wrong fact is not a gate. This asserts the property that
        replaced it: with no answer from the sentinel, the result is False
        (do not kill) regardless of pids or start method.
        """
        import multiprocessing

        from cognee_db_workers import harness

        monkeypatch.setattr(harness, "_parent_sentinel_alive", lambda: None)
        bogus_baseline = 999999
        assert os.getppid() != bogus_baseline, "baseline must differ for this to mean anything"

        # Under EVERY start method -- including the ones the old fallback
        # treated as safe -- an unanswerable sentinel must never yield "dead".
        for method in ("spawn", "fork", "forkserver"):
            monkeypatch.setattr(
                multiprocessing, "get_start_method", lambda allow_none=False, _m=method: _m
            )
            assert harness.parent_already_exited(bogus_baseline) is False, (
                f"under {method}: no sentinel answer must mean unknown, not dead. "
                "Returning True here kills healthy workers."
            )

    def test_invalid_sentinel_fd_is_unknown_not_dead(self):
        """A closed/invalid sentinel fd must degrade to None, never False.

        `is_alive()` does NOT raise on a bad fd: selectors accept any
        non-negative int, poll() reports POLLNVAL, and the selector treats that
        as ready -- so `is_alive()` returns False, i.e. "confirmed dead", for a
        perfectly healthy parent. The docstring used to claim every error path
        returned None; it did not, and that claim guarded an os._exit(0).
        """
        import multiprocessing

        from cognee_db_workers import harness

        r, w = os.pipe()
        os.close(r)
        os.close(w)

        class _BadFdParent:
            _sentinel = r

            def is_alive(self):
                return False  # what POLLNVAL actually produces

        original = multiprocessing.parent_process
        multiprocessing.parent_process = lambda: _BadFdParent()
        try:
            got = harness._parent_sentinel_alive()
        finally:
            multiprocessing.parent_process = original

        assert got is None, (
            f"invalid fd yielded {got!r}; False would be read as 'parent dead' "
            "and kill a worker whose parent is fine"
        )


class TestSentinelWatchdogUnitSemantics:
    """Fail-safe contract of the anchoring / sentinel-watchdog helpers.

    The live-subprocess test above proves the watchdog FIRES. These prove the
    much more dangerous direction -- that it does not fire when it must not.
    A false positive here is `os._exit(0)` on a healthy worker, i.e. an outage,
    and none of the failure modes below are reachable from a spawn test.

    Every stub parent below reports `is_alive() -> True`. That is a safety
    property of the test suite, not an incidental detail: under a MUTANT that
    lets an unwanted watcher start, the thread is real and polls inside the
    pytest process, so a stub that read "dead" would `os._exit(0)` the test
    runner itself and report as a crash rather than a failure.
    """

    @pytest.fixture(autouse=True)
    def _isolate_watchdog_state(self):
        """Per-test isolation of the module-global watchdog state.

        Added 2026-07-29 after a mutation run: a mutant that wrongly starts a
        watcher leaks BOTH the module flag and a live daemon thread into every
        later test, so mutating one guard turned three unrelated tests red and
        the evidence stopped being attributable. Tests here must fail for their
        own reason or the mutation signal is worthless.
        """
        from cognee_db_workers import harness

        saved = harness._sentinel_watchdog_started
        self._thread_baseline = _watchdog_thread_count()
        try:
            yield
        finally:
            harness._sentinel_watchdog_started = saved

    def assert_no_new_watchdog_thread(self, why: str) -> None:
        """No watcher thread was started BY THIS TEST (delta, not absolute)."""
        now = _watchdog_thread_count()
        assert now == self._thread_baseline, (
            f"{why} (watcher threads: {self._thread_baseline} before, {now} after)"
        )

    def test_anchor_is_unknown_outside_a_multiprocessing_child(self):
        """No baseline means no claim -- not "mismatched"."""
        from cognee_db_workers import harness

        # The main process is not a multiprocessing child, so there is no real
        # parent to compare getppid() against.
        assert harness.get_original_parent_pid() is None
        assert harness.pdeathsig_anchor_is_real_parent() is None

    def test_anchor_compares_getppid_to_the_real_parent(self, monkeypatch):
        """True only when the OS parent IS the launching process.

        Both directions matter. A function stuck at True would silently skip the
        watchdog and leave the forkserver gap open; one stuck at False would
        start a redundant polling thread under spawn/fork. Measured on WSL
        Ubuntu / CPython 3.14.4 with the parent alive throughout::

            spawn        parent_process().pid=6319  getppid()=6319  -> True
            fork         parent_process().pid=6319  getppid()=6319  -> True
            forkserver   parent_process().pid=6319  getppid()=6325  -> False
        """
        from cognee_db_workers import harness

        monkeypatch.setattr(harness, "get_original_parent_pid", lambda: os.getppid())
        assert harness.pdeathsig_anchor_is_real_parent() is True

        bogus = os.getppid() + 1000000
        monkeypatch.setattr(harness, "get_original_parent_pid", lambda: bogus)
        assert harness.pdeathsig_anchor_is_real_parent() is False

    def test_watchdog_reports_false_when_there_is_nothing_to_watch(self):
        """Returning True while watching nothing is the lie this file exists to kill.

        In the main process there is no multiprocessing parent and therefore no
        sentinel, so the watchdog must decline to start AND say so. Reporting
        success here would reproduce, one layer down, exactly the
        `set_pdeathsig()` -> True -> fallback-suppressed failure that made the
        forkserver gap invisible in the first place.
        """
        from cognee_db_workers import harness

        assert harness.start_parent_sentinel_watchdog() is False
        assert not any(
            t.name == "parent-sentinel-watchdog" for t in threading.enumerate()
        ), "a watcher thread was started even though there is no sentinel to watch"

    @pytest.mark.parametrize("verdict", [True, None])
    def test_only_a_confirmed_dead_sentinel_counts_as_death(self, monkeypatch, verdict):
        """Alive AND unknown must both yield False. Only False means dead."""
        from cognee_db_workers import harness

        monkeypatch.setattr(harness, "_parent_sentinel_alive", lambda: verdict)
        assert harness._sentinel_confirms_parent_dead(None) is False
        assert harness._sentinel_confirms_parent_dead((1, 2)) is False

    def test_confirmed_dead_with_matching_identity_is_death(self, monkeypatch):
        """The one case that MAY kill: corroborated dead AND identity matches."""
        from cognee_db_workers import harness

        monkeypatch.setattr(harness, "_parent_sentinel_alive", lambda: False)
        monkeypatch.setattr(harness, "_parent_sentinel_identity", lambda: (7, 42))
        assert harness._sentinel_confirms_parent_dead((7, 42)) is True

    def test_unpinned_is_never_death_even_when_the_sentinel_says_dead(self, monkeypatch):
        """No pin means the recycled-fd case cannot be ruled out -> not dead.

        INVERTED 2026-07-29. This assertion previously read `is True`, with the
        rationale that falling back to `_parent_sentinel_alive()`'s own
        corroboration was "never weaker than what parent_already_exited does at
        startup". That was a category error: parent_already_exited is ONE-SHOT
        at startup, the watchdog POLLS FOREVER. Same reading, different
        exposure. A passing test asserting `is True` did not make the behaviour
        safe -- it enshrined the hole and made it look deliberate, which is
        worse than leaving it uncovered.

        Note this test goes red against BOTH directions of the bug: a `True`
        here is the outage, and it is the exact value the code used to return.
        """
        from cognee_db_workers import harness

        monkeypatch.setattr(harness, "_parent_sentinel_alive", lambda: False)
        monkeypatch.setattr(harness, "_parent_sentinel_identity", lambda: (7, 42))
        assert harness._sentinel_confirms_parent_dead(None) is False, (
            "an unpinnable sentinel was read as a parent death; this is os._exit(0) "
            "on a worker whose parent is perfectly healthy"
        )

    def test_watchdog_refuses_to_start_when_the_fd_cannot_be_pinned(self, monkeypatch):
        """An unpinned watcher can never fire, so it must never exist.

        Second half of the same fix. Without this, `start_parent_sentinel_watchdog`
        checked only that `_sentinel` was not None and would happily run
        permanently unpinned. Declining is strictly better than a thread that
        polls forever and cannot act -- a protection that exists only on paper.
        """
        import multiprocessing

        from cognee_db_workers import harness

        class _Parent:
            _sentinel = 0

            def is_alive(self):
                return True

        monkeypatch.setattr(multiprocessing, "parent_process", lambda: _Parent())
        monkeypatch.setattr(harness, "_parent_sentinel_identity", lambda: None)
        assert harness.start_parent_sentinel_watchdog() is False
        self.assert_no_new_watchdog_thread("a permanently-unpinned watcher thread was started")

    def test_watchdog_is_posix_only_by_enforcement_not_by_accident(self, monkeypatch):
        """Windows must be refused by the explicit guard, not by circumstance.

        `_parent_sentinel_identity` returns None on Windows BY DESIGN (`_sentinel`
        is a process HANDLE, not an fd), so a Windows watcher could only ever be
        the unpinned kind. Before the explicit guard the POSIX scoping held only
        because `run_worker_loop` happened never to reach it there -- true, but
        unenforced, and one new caller away from being false. Mirrors
        `parent_already_exited`, which opens with the same check.

        CORRECTED 2026-07-29 -- this test was WORTHLESS as first written. It set
        `platform` and asserted False, but in the main pytest process
        `parent_process()` is None, so it returned False via the "nothing to
        watch" path and never reached the win32 guard at all. A mutation run
        that DELETED the guard left this test GREEN, which is how it was caught:
        mutation proves a guard is load-bearing, never that it was consulted.
        Now every other exit is stubbed out -- valid parent, valid sentinel,
        successful pin -- so the win32 check is the ONLY thing left that can
        return False, and deleting it makes this go red.
        """
        import multiprocessing

        from cognee_db_workers import harness

        class _Parent:
            _sentinel = 0

            def is_alive(self):
                return True  # never let a mutant-started thread exit pytest

        monkeypatch.setattr(multiprocessing, "parent_process", lambda: _Parent())
        monkeypatch.setattr(harness, "_parent_sentinel_identity", lambda: (7, 42))
        monkeypatch.setattr(harness, "_sentinel_watchdog_started", False)
        # Sanity: with POSIX these stubs DO start a watcher, so the win32 result
        # below is attributable to the guard and nothing else. This deliberately
        # leaks ONE daemon thread for the rest of the session -- the watchdog has
        # no stop signal by design (it is meant to outlive everything until the
        # process dies). It is inert: once monkeypatch unwinds, its pinned
        # identity can never match, so `_sentinel_confirms_parent_dead` returns
        # False forever. This is why the assertions here and in the sibling tests
        # count a DELTA rather than asserting an absolute zero.
        monkeypatch.setattr(harness.sys, "platform", "linux")
        assert harness.start_parent_sentinel_watchdog() is True, (
            "the stubs do not reach the start path, so this test cannot isolate "
            "the win32 guard -- fix the stubs, not the assertion"
        )

        monkeypatch.setattr(harness, "_sentinel_watchdog_started", False)
        monkeypatch.setattr(harness.sys, "platform", "win32")
        before = _watchdog_thread_count()
        assert harness.start_parent_sentinel_watchdog() is False, (
            "the win32 guard is absent: Windows would run a permanently-unpinned "
            "watcher, since _parent_sentinel_identity returns None there by design"
        )
        assert _watchdog_thread_count() == before, "a watcher was started on win32"

    def test_watchdog_is_idempotent(self, monkeypatch):
        """Re-entering run_worker_loop must not accumulate watcher threads."""
        from cognee_db_workers import harness

        monkeypatch.setattr(harness, "_sentinel_watchdog_started", True)
        # Reports True -- a watcher IS running -- without starting a second one,
        # so the caller's "did this leave me unprotected?" check stays correct.
        assert harness.start_parent_sentinel_watchdog() is True
        self.assert_no_new_watchdog_thread("idempotence guard did not prevent a second thread")

    def test_recycled_sentinel_fd_is_not_read_as_parent_death(self, monkeypatch):
        """The failure mode the identity pin exists for.

        `_parent_sentinel_alive()` corroborates a "dead" answer by checking the
        fd is still VALID, which rejects a CLOSED fd. It cannot reject a
        RECYCLED one: if the sentinel fd is closed and a later open() is handed
        the same fd NUMBER, fstat succeeds, poll() on a regular file always
        reports readable, and is_alive() returns False for a perfectly healthy
        parent -- a fully corroborated, completely wrong "dead".

        As a one-shot startup check that window is narrow. The watchdog polls
        for the worker's whole life, so it gets the pin instead: a sentinel
        whose identity no longer matches the one captured at start is UNKNOWN,
        never dead.
        """
        from cognee_db_workers import harness

        monkeypatch.setattr(harness, "_parent_sentinel_alive", lambda: False)
        monkeypatch.setattr(harness, "_parent_sentinel_identity", lambda: (7, 99))
        assert harness._sentinel_confirms_parent_dead((7, 42)) is False, (
            "a recycled sentinel fd was read as a parent death; this kills a worker "
            "whose parent is perfectly healthy"
        )

    def test_recycled_sentinel_fd_with_REAL_fds_and_the_real_is_alive(self, monkeypatch):
        """The same failure, measured rather than simulated.

        The test above stubs `_parent_sentinel_alive`, so it proves the
        predicate's arithmetic but takes the premise on faith. This one builds
        the situation out of real file descriptors and calls the REAL
        `multiprocessing.process._ParentProcess.is_alive()` -- the same code path
        a live worker runs -- so it also proves the premise: that a recycled fd
        genuinely does read as "parent dead" while the parent is alive.

        `os.dup2` is what makes it deterministic: it forces a DIFFERENT open file
        description onto the SAME fd number, which is exactly what a close +
        later open would do by luck.

        The `pinned=None` assertion at the end is the F1 regression guard in its
        realistic setting: the parent here is this very test process, alive
        beyond doubt, and an unpinned check used to answer "dead" -- i.e.
        `os._exit(0)` mid-test-suite had the watchdog been the caller.
        """
        import multiprocessing
        from multiprocessing.process import _ParentProcess

        from cognee_db_workers import harness

        r, w = os.pipe()
        st = os.fstat(r)
        good_identity = (st.st_dev, st.st_ino)
        scratch = open(os.devnull, "rb")
        try:
            os.close(w)
            # Recycle the fd NUMBER onto an unrelated open file description.
            os.dup2(scratch.fileno(), r)
            parent = _ParentProcess("MainProcess", os.getpid(), r)
            monkeypatch.setattr(multiprocessing, "parent_process", lambda: parent)

            # PREMISE: the real is_alive() calls this healthy parent dead.
            assert parent.is_alive() is False, (
                "premise failed: a recycled fd did not read as dead on this platform, "
                "so the rest of this test would prove nothing"
            )
            # And the existing validity corroboration does NOT catch it -- the
            # fd is perfectly valid, it is just a different file now.
            assert harness._parent_sentinel_alive() is False

            # THE PIN CATCHES IT.
            assert harness._sentinel_confirms_parent_dead(good_identity) is False, (
                "identity pin failed to reject a recycled fd"
            )
            # AND SO DOES THE ABSENCE OF A PIN. Ambiguity is never death.
            assert harness._sentinel_confirms_parent_dead(None) is False, (
                "unpinned check called a healthy parent dead -- this is the F1 outage"
            )
        finally:
            os.close(r)
            scratch.close()
